name: C++ CI Pipeline

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt update && sudo apt install g++ -y

    - name: Compile main.cpp
      run: g++ Akhir.cpp -o main

    - name: Run the program
      run: ./main
